### PR TITLE
add svelte ✌🏼

### PR DESCRIPTION
**Pull request by fernandolguevara**

### CODE REVIEW

**Comment by adamwathan** [comment]
Hey! I think this is the third time we’ve gotten this PR 😅

For now I think this would best be handled as a third-party package, just because I don't want to commit to maintaining this ourselves going forward as none of the maintainers actively use Svelte.

Sorry, hope that's understandable and thanks again regardless, really appreciate it.

**Comment by fernandolguevara** [comment]
wow that's a shame the package for svelte has no complexity and would be a great help to the community.

**Comment by adamwathan** [comment]
You are more than welcome to publish a package for it and maintain it 👍🏻 We don’t really open source anything as a service, we do it because we are using this code ourselves and figure why not make it available to everyone. As a rule though we don’t build and release things we don’t use ourselves, we already do kind of a crappy job maintaining these packages because we are too busy with Tailwind and Headless UI. Better for someone who actually would be using it to publish their own package and share it with the community, then it will actually be properly maintained 👍🏻

**Comment by carloslfu** [comment]
I agree with Adam! For reference for anyone coming here. After looking for packages for a bit, I really liked https://github.com/steeze-ui/icons by @JustinVoitel. It supports more frameworks, and it uses Heroicons 2.0.

**Pull request closed without merging**
