### PR TITLE
feat: type declarations for vue

### LINKED ISSUE #252: TS7016: Could not find a declaration file for module '@heroicons/vue/solid'.
When we are using the library in typescript, everything works perfectly, but it is not defined.

image

### PR DESCRIPTION
**Pull request by VottusCode**
fixes #252 

Until this is merged, I've published a package heroicons-vue3,
which will be deprecated (but will continue to work, however unmaintained) once it is merged. If you need to use Heroicons with Vue 3 now, you can use that for the time being.

### CODE REVIEW

**Review by dacoto97 — APPROVED** [review]

**Comment by VottusCode** [comment]
Can this be merged, please?

**Comment by cal97g** [comment]
This fixes broken support for tailwind UI and was approved a month ago. Pls merge.

**Comment by dystopiandev** [comment]
How this PR has remained unmerged for so long is beyond my comprehension.

**Comment by davidmatter** [comment]
@bradlc @dacoto97 can we have a merge here? :)

**Comment by NotHolst** [comment]
Why did this die after being approved?

**Comment by VottusCode** [comment]
no idea

**Comment by bartenra** [comment]
Pinging @bradlc and @adamwathan again.

**Comment by VottusCode** [comment]
@bradlc @adamwathan Please can you merge this?

**Review by dacoto97 — APPROVED** [review]

**Comment by RobinMalfait** [comment]
Hey! Thank you for your PR!
Much appreciated! 🙏

Sorry for the delay!

**Pull request merged**
