### PR TITLE
Add composer.json

### PR DESCRIPTION
**Pull request by simonhamp**
Add Composer support so you can put Heroicons on Packagist, to allow PHP projects to import them without the use of other package managers.

### CODE REVIEW

**Comment by simonhamp** [comment]
And once this is added, could you register the repo on Packagist? Context for me is in a Statamic add-on, which can't easily use direct GitHub repos for dependency management (at least until v3).

**Comment by driesvints** [comment]
@simonhamp made this package which might be of interest to you: https://github.com/driesvints/blade-heroicons

**Comment by simonhamp** [comment]
@driesvints Nice! I will definitely look into this in more detail, but on a quick first pass I’m not sure it’s going to work with Statamic yet as that’s still running on Laravel 5.1 right now.

Also I was thinking of something that would be flexible to changes with the Heroicons library so that new/changed icons didn’t require code changes.

**Comment by driesvints** [comment]
> still running on Laravel 5.1 right now.

I'd recommend upgrading soon because I don't even want to know how many security vulnerabilities there are with 5.1 😅

> Also I was thinking of something that would be flexible to changes with the Heroicons library so that new/changed icons didn’t require code changes.

You wouldn't have to change your own icons you use in your app since all changes would be done in the `blade-heroicons` package. Every time you composer update you'd get any fixes, new icons, etc. I'll regularly keep the library up to date.

**Comment by simonhamp** [comment]
Agreed! We’re holding out for Statamic 3 as manually upgrading ourselves would cause us more pain at this point.

You’ve made a great case. Thanks for sharing this and for writing the library. I’ll let you know how I get on.

I still think it would be good to have Heroicons available as a Composer dependency tho. /cc @steveschoger @adamwathan

**Comment by driesvints** [comment]
> I still think it would be good to have Heroicons available as a Composer dependency tho.

I think that's not feasible as this is a NPM library at first. You wouldn't be able to use the SVG icons in Blade anyway because they're `.svg` files. You'd have to `file_get_contents` them. And if you add them as PHP/Blade files then people using them with NPM would have the burdon of having to retrieve and compile all of those files as well.

I've added the ability in Blade Heroicons to use the heroicons as raw SVG icons if that's what you're looking for: https://github.com/driesvints/blade-heroicons#raw-svg-icons

**Comment by simonhamp** [comment]
> I think that's not feasible

I don’t see why not. Just putting this library on Packagist will just make it available as a dependency, same as NPM. There’s nothing inherent here that makes it specific to NPM.

> they’re `.svg` files. You'd have to `file_get_contents` them.

I know. That’s exactly what I plan to do 🙂 would save the burden of duplicating them in Blade. Then when Heroicons gets updated, my code will also get updated... for “free”.

**Pull request closed without merging**
