### PR TITLE
Removed white background

### PR DESCRIPTION
**Pull request by podpage**
Removed white background in outline version of _academicCap_ and _truck_

### CODE REVIEW

**Comment by simensen** [comment]
Ran into this myself. Found a couple of icons that needed to be tweaked. Tried using `<x-heroicon-o-academic-cap />` and it looked wayyy off. Had to tweak it by hand.

Honestly, though, at least for academic cap, do we even need the first two lines of the SVG? It appears to render just fine for me if I straight up remove them. I don't know enough about SVG to know why they might be important, though.

**Comment by clarkewing** [comment]
@adamwathan any chance of getting this merged?

**Comment by adamwathan** [comment]
I'll happily merge it but you shouldn't even be using the `src` folder, you want the `optimized` folder where all this stuff is processed and that sort of thing is removed already:

https://github.com/tailwindlabs/heroicons/blob/master/optimized/outline/academic-cap.svg?short_path=c23120b

**Comment by clarkewing** [comment]
Thanks for such a speedy resolve! Could I ask when the icons are processed and those in `optimized` updated?

I'm encountering issues using the icons "as is" over colored backgrounds with [blade-ui-kit/blade-heroicons](https://github.com/blade-ui-kit/blade-heroicons) as I have not direct control over the SVG file without exporting everything.

**Comment by adamwathan** [comment]
No worries! Right now it's just kinda manually whenever there's an update. We haven't been able to give this project a ton of attention in the last few months but hoping to clean it up and put some better processes in place soon.

**Comment by driesvints** [comment]
@adamwathan a composer.json and publishing it to packagist would be greatly appreciated. That way we can directly import it in blade-heroicons and publish updates sooner :)

**Pull request merged**
