### PR TITLE
✨ Compile React components for direct import

### PR DESCRIPTION
**Pull request by brandonpittman**
As it is now, the React components aren't compiled and thus can't be imported from the heroicons package. This PR will let users import them like so…

```js
import { Menu, X } from "heroicons/react/solid
import { Menu as MenuOutline } from "heroicons/react/outline"
```

### CODE REVIEW

**Comment by adamwathan** [comment]
Hey,  yeah right now I was just hacking on some stuff to use in Vite which does support running this stuff right through the dev server, the current Vue/React versions of these icons aren't really "released" yet which is why they aren't documented :)

I noticed in the diff though it looks like the entire source code of React is embedded in the React icons, is this intentional?

**Comment by brandonpittman** [comment]
@adamwathan No, just the first time I used Rollup to create a React component library. Sorry about that.

**Comment by adamwathan** [comment]
Don't be sorry I have literally no idea how to do it either 😅

**Comment by brandonpittman** [comment]
@adamwathan I’ll take another stab at it tomorrow.

**Comment by brandonpittman** [comment]
@adamwathan I think I got all that React code out of there.

**Comment by SimonPrague** [comment]
Does this add support for Vue? As that would be awesome.

I looked at https://github.com/matschik/vue-hero-icons and https://github.com/imhassane/heroicons-vue but they don't look production ready and have poor TypeScript support.

**Pull request closed without merging**
