### PR TITLE
add smart-phone icon

### PR DESCRIPTION
**Pull request by claretnnamocha**
Adding a smartphone icon in response to @taylorotwell request

### CODE REVIEW

**Comment by claretnnamocha** [comment]
@adamwathan

**Comment by jsmith** [comment]
See https://twitter.com/steveschoger/status/1283144200675090433. Steve will be adding a smartphone icon soon!

**Comment by claretnnamocha** [comment]
thanks for the info @jsmith, I'll be closing this pr

**Comment by jsmith** [comment]
No problem :)

**Pull request closed without merging**
